PROG=		test
SRCS=		test.c
OBJS=		test.o

LIBS=		-lm -lpthread -lebpf -L${LIBEBPFDIR}
CPPFLAGS=	-I ${BASE}/sys
CFLAGS+=	${CPPFLAGS} -O0 -coverage
LDFLAGS+=	-coverage

all: ${PROG}
${PROG}: ${OBJS} ${LIBEBPF}
	$(CC) -o $@ ${LDFLAGS} ${OBJS} ${LIBS}

check:
	env LD_LIBRARY_PATH=$(LIBEBPFDIR) PYTHONPATH=${BASE}/tools nosetests

CLEANFILES=	$(PROG) $(OBJS) *.gcno *.gcda
