PROG=		test
SRCS=		test.c
OBJS=		test.o

LIBS=		-lm -lpthread -lebpf -L${BASE}
CPPFLAGS=	-I ${BASE}/sys
CFLAGS+=	${CPPFLAGS} -O0 -coverage
LDFLAGS+=	-coverage

all: ${PROG}
${PROG}: ${OBJS}
	$(CC) -o $@ ${LDFLAGS} ${OBJS} ${LIBS}

check:
	env LD_LIBRARY_PATH=$(BASE) PYTHONPATH=${BASE}/tools ./${PROG}

CLEANFILES=	$(PROG) $(OBJS) *.gcno *.gcda
