PROG=	printer
SRCS=	printer.c
OBJS=	${SRCS:.c=.o}
LIBS=	${LIBGBPF} -lelf
CPPFLAGS= \
	-O3 \
	-I ${BASE}/sys \
	-I ${CURDIR}/../include \
	-Wall
CFLAGS+=$(CPPFLAGS)

all: ${PROG}

${PROG}: ${OBJS} ${LIBGBPF}
	$(CC) -o $@ $(CFLAGS) $(OBJS) $(LIBS)
CLEANFILES+=	${PROG} ${OBJS}
