PROG=	all_tests
OBJS=	$(map_tests) $(prog_tests) $(GTESTOBJS)
CXXFLAGS+= \
	-I $(BASE)/sys \
	-I $(LIBEBPFDIR) \
	-I $(GTESTPATH)/googletest/include \
	-I $(CKPATH)/include \
	-Wno-unused-command-line-argument \
	-Wno-unused-variable \
	-O0 \
	$(LDFLAGS)
LDFLAGS+=-coverage
LIBS=	-lpthread -lebpf -L${LIBEBPFDIR}

map_tests = \
	map_create_test.o \
	map_lookup_test.o \
	map_update_test.o \
	map_delete_test.o \
	map_get_next_key_test.o \
	array_map_delete_test.o \
	array_map_get_next_key_test.o \
	array_map_lookup_test.o \
	array_map_update_test.o \
	percpu_array_map_delete_test.o \
	percpu_array_map_get_next_key_test.o \
	percpu_array_map_lookup_test.o \
	percpu_array_map_update_test.o

all: $(PROG)
$(PROG): $(OBJS) ${LIBEBPF}
	$(CXX) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

check:
	-LD_LIBRARY_PATH=$(LIBEBPFDIR) ./$(PROG)

CLEANFILES=	$(PROG) $(OBJS) *.gcda *.gcno
