#!/usr/bin/env python
"""
eBPF disassembler

Reads the given file or stdin. The input should be raw eBPF
instructions (not an ELF object file).
"""

import argparse
import os
import sys

import ebpf.disassembler

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('input', type=argparse.FileType('r'), default='-')
    parser.add_argument('output', type=argparse.FileType('w'), default='-')
    args = parser.parse_args()

    args.output.write(ebpf.disassembler.disassemble(args.input.read()))

if __name__ == "__main__":
    main()
