#!/usr/bin/env python
"""
eBPF assembler

Very simple single-pass assembler. Only exists to assemble testcases
for the interpreter.
"""

import argparse
import os
import sys

import ebpf.assembler

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('input', type=argparse.FileType('r'), default='-')
    parser.add_argument('output', type=argparse.FileType('w'), default='-')
    args = parser.parse_args()

    args.output.write(ebpf.assembler.assemble(args.input.read()))

if __name__ == "__main__":
    main()
