PROG=	all_tests
OBJS=	$(map_tests) $(prog_tests) ${GTESTOBJS}
CXXFLAGS+= \
	-I $(BASE)/sys \
	-I $(LIBEBPFDIR) \
	-I $(GTESTPATH)/googletest/include \
	-Wno-unused-command-line-argument \
	-O0 \
	$(LDFLAGS)
LDFLAGS+=-coverage
LIBS=	-lpthread -L${BASE}

map_tests = \
	ebpf_dev_map_create_test.o \
	ebpf_dev_map_update_elem_test.o \
	ebpf_dev_map_lookup_elem_test.o \
	ebpf_dev_map_delete_elem_test.o \
	ebpf_dev_map_get_next_key_test.o \
	ebpf_dev_hashtable_map_test.o \
	ebpf_dev_percpu_hashtable_map_test.o \
	ebpf_dev_get_map_type_info_test.o

prog_tests = \
	ebpf_dev_prog_load_test.o \
	ebpf_dev_run_test_test.o

all: $(PROG)
$(PROG): $(OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

check:
	-LD_LIBRARY_PATH=$(BASE) ./$(PROG)

CLEANFILES=	$(PROG) $(OBJS) *.gcda *.gcno
